---
title: "wk4"
author: "phil"
date: "2022-10-28"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(dplyr)
library(sf)
library(fs)
library(terra)
library(usethis)
library(here)
library(janitor)
library(tmap)
library(tmaptools)
library(countrycode)
```


```{r}
gii <- read_csv(here('table.csv')) %>%
  dplyr::select(iso3, country, gii_2010, gii_2019)
  

```


```{r}
# import shape file
shape <- st_read('https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/World_Countries_(Generalized)/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson') %>%
  clean_names() %>% select(-country, -iso)

#shape1 <- st_read(here('raw_data', 'World_Countries_(Generalized).geojson'))
```


```{r}
# convert iso3 to iso2
gii$iso2 <- countrycode(gii$iso3, 'iso3c', 'iso2c' )

gii


```


```{r}
# merge shape and csv data
merged_data <- shape %>%
  merge(.,
        gii,
        by.x = 'aff_iso',
        by.y = 'iso2',
        no.dups = T) 
```


```{r}
# diff between 2010 and 2019
merged_data_diff <- merged_data %>% 
  mutate(diff = gii_2019 - gii_2010) %>%
  select_all() %>% print()

```
